"""initial setup

Revision ID: bcdee1d15af5
Revises: 
Create Date: 2022-11-20 14:45:06.806617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdee1d15af5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('cis', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('producer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cis')
    )
    op.create_table('default_bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_a', sa.Integer(), nullable=True),
    sa.Column('chat', sa.Integer(), nullable=True),
    sa.Column('poll', sa.Integer(), nullable=True),
    sa.Column('survey', sa.Integer(), nullable=True),
    sa.Column('raise_hand', sa.Integer(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.Column('left_aligned', sa.Integer(), nullable=True),
    sa.Column('right_aligned', sa.Integer(), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slido_event_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.Text(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('cis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cis_id'], ['projects.cis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    op.drop_table('socials')
    op.drop_table('slido_event_codes')
    op.drop_table('slido')
    op.drop_table('name_keys')
    op.drop_table('default_bugs')
    op.drop_table('projects')
    # ### end Alembic commands ###
